# Generated by Django 5.2.1 on 2026-04-19 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='executivecommittee',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committee.committeetitle'),
        ),
        migrations.AddConstraint(
            model_name='executivecommittee',
            constraint=models.UniqueConstraint(condition=models.Q(('position__isnull', False)), fields=('user', 'committee', 'position', 'executive_year'), name='unique_with_position'),
        ),
        migrations.AddConstraint(
            model_name='executivecommittee',
            constraint=models.UniqueConstraint(condition=models.Q(('position__isnull', True)), fields=('user', 'committee', 'executive_year'), name='unique_without_position'),
        ),
    ]
