# Generated by Django 5.2.1 on 2026-04-23 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastExecutiveCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='home/committee/images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PastSubCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='home/committee/images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='executivecommittee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='committeename',
            name='is_show_past_sub_committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_committees', to='committee.committeename'),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='executive_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_committees', to='committee.committeeyear'),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='executivecommittee',
            constraint=models.UniqueConstraint(fields=('user', 'committee', 'executive_year'), name='unique_user_committee_year'),
        ),
        migrations.RemoveField(
            model_name='executivecommittee',
            name='position',
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='executive_committees', to='committee.committeetitle'),
        ),
    ]
