# Generated by Django 5.2.1 on 2026-04-19 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_alter_executivecommittee_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='executivecommittee',
            name='unique_with_position',
        ),
        migrations.RemoveConstraint(
            model_name='executivecommittee',
            name='unique_without_position',
        ),
        migrations.RemoveField(
            model_name='executivecommittee',
            name='position',
        ),
        migrations.AddConstraint(
            model_name='executivecommittee',
            constraint=models.UniqueConstraint(fields=('user', 'committee', 'executive_year'), name='unique_user_committee_year'),
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='executive_committees', to='committee.committeetitle'),
        ),
    ]
