# Generated by Django 5.2.1 on 2026-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_remove_executivecommittee_unique_with_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeename',
            name='is_show_past_sub_committee',
            field=models.BooleanField(default=False),
        ),
    ]
