# Generated by Django 5.2.1 on 2026-04-19 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_committeename_is_show_past_sub_committee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivecommittee',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_committees', to='committee.committeename'),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='executive_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_committees', to='committee.committeeyear'),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_committees', to=settings.AUTH_USER_MODEL),
        ),
    ]
