# Generated by Django 5.2.1 on 2026-01-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='title',
            new_name='Property_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='dining_rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_feet',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='property',
            name='exterior_feature',
            field=models.CharField(choices=[('brick', 'Brick'), ('veneer', 'Veneer')], default='brick', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='living_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Living Area'),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Square Feet'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_Demographic_Profile',
            field=models.CharField(choices=[('White (Non-Hispanic)', 'White (Non-Hispanic)'), ('Black or African American', 'Black or African American'), ('Asian', 'Asian'), ('Hispanic or Latino', 'Hispanic or Latino')], default='White (Non-Hispanic)', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Neighborhood Percentage'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('single_family', 'Single Family'), ('double_family', 'Double Family')], default='single_family', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='year_build',
            field=models.IntegerField(blank=True, null=True, verbose_name='year build'),
        ),
    ]
