# Generated by Django 5.2.1 on 2026-01-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_title_property_property_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Property_name',
            new_name='property_name',
        ),
    ]
