# Generated by Django 5.2.1 on 2026-01-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.FloatField(blank=True, null=True, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('wishlist', 'Wish List'), ('failed_to_bought', 'Failed to bought'), ('move_to_next_option', 'Move to next Auction'), ('bought', 'Bought'), ('ready_to_sell', 'Ready to sell'), ('sold', 'Sold')], default='wishlist', max_length=20, null=True),
        ),
    ]
