# Generated by Django 5.2.1 on 2026-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_property_bathrooms_alter_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
