# Generated by Django 5.2.1 on 2026-02-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_property_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='exterior_feature',
            field=models.CharField(choices=[('brick', 'Brick'), ('wood_frame', 'Wood Frame'), ('brick_veneer', 'Brick Veneer over Wood Frame'), ('cmu', 'Concrete Block (CMU)'), ('stone', 'Stone')], default='brick', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('single_family', 'Single-Family House'), ('rowhouse', 'Rowhouse'), ('condo', 'Condo'), ('duplex', 'Duplex')], default='single_family', max_length=20),
        ),
    ]
