# Generated by Django 5.2.1 on 2026-02-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_property_exterior_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('wishlist', 'Wish List'), ('failed_to_bought', 'Failed to bought'), ('move_to_next_option', 'Move to next Auction'), ('bought', 'Bought'), ('ready_to_sell', 'Ready to sell'), ('sold', 'Sold'), ('stayed', 'Stayed')], default='wishlist', max_length=20, null=True),
        ),
    ]
