# Generated by Django 5.2.1 on 2026-03-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='exterior_feature',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('wood_frame', 'Wood Frame'), ('brick_veneer', 'Brick Veneer over Wood Frame'), ('cmu', 'Concrete Block (CMU)'), ('stone', 'Stone')], default='brick', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood_Demographic_Profile',
            field=models.CharField(blank=True, choices=[('White (Non-Hispanic)', 'White (Non-Hispanic)'), ('Black or African American', 'Black or African American'), ('Asian', 'Asian'), ('Hispanic or Latino', 'Hispanic or Latino')], default='White (Non-Hispanic)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('single_family', 'Single-Family House'), ('rowhouse', 'Rowhouse'), ('condo', 'Condo'), ('duplex', 'Duplex')], default='single_family', max_length=20, null=True),
        ),
    ]
