# Generated by Django 5.2.1 on 2026-04-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_committee',
            field=models.BooleanField(default=False, verbose_name='Is Committee'),
        ),
    ]
