# Generated by Django 5.2.1 on 2026-04-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_committee_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_us_based',
            field=models.BooleanField(default=True, verbose_name='Is your Home Address U.S. Based?'),
        ),
        migrations.AddField(
            model_name='user',
            name='not_usa_phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='not_usa_state',
            field=models.CharField(max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='user',
            name='province_region_territory',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_postalcode_ext',
            field=models.CharField(max_length=15, null=True, verbose_name='ZIP Code Ext'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=10, null=True, verbose_name='ZIP Code'),
        ),
    ]
