# Generated by Django 5.2.1 on 2026-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_committee_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(max_length=100, null=True, verbose_name='Division'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_us_based',
            field=models.BooleanField(default=True, verbose_name='Is your Home Address U.S. Based?'),
        ),
        migrations.AddField(
            model_name='user',
            name='upazila_thana',
            field=models.CharField(max_length=200, null=True, verbose_name='Upazila,Thana If Available'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=10, null=True, verbose_name='ZIP Code'),
        ),
    ]
