# Generated by Django 5.2.1 on 2026-05-11 17:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_country_user_country_code_user_is_us_based_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('wishlist', 'Wish List'), ('failed_to_bought', 'Failed to bought'), ('move_to_next_option', 'Move to next Auction'), ('bought', 'Bought'), ('rented', 'Rented'), ('ready_to_sell', 'Ready to sell'), ('sold', 'Sold'), ('stayed', 'Stayed')], default='wishlist', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RentalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.DateField(help_text='Use first day of the month, example: 2026-01-01', verbose_name='Bill Month')),
                ('rent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total rental expense for this month', max_digits=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_rental_bills', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_bills', to='accounts.property')),
            ],
            options={
                'verbose_name': 'Rental Bill',
                'verbose_name_plural': 'Rental Bills',
                'ordering': ['-bill_month', '-created_at'],
                'unique_together': {('property', 'bill_month')},
            },
        ),
        migrations.CreateModel(
            name='RentalBillDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50)),
                ('month_days', models.PositiveIntegerField(default=0)),
                ('days_proportion', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('shares', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('base_weight', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('buyer_level', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('final_weight', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50)),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50)),
                ('final_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50)),
                ('loss_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_distributions', to='accounts.propertycontribution')),
                ('rental_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_lines', to='accounts.rentalbill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Bill Distribution',
                'verbose_name_plural': 'Rental Bill Distributions',
                'ordering': ['rental_bill', 'user', 'id'],
            },
        ),
    ]
