# Generated by Django 5.2.1 on 2026-04-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_country_user_country_code_user_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upazila_thana',
        ),
        migrations.AddField(
            model_name='user',
            name='province_region_territory',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_postalcode_ext',
            field=models.CharField(max_length=15, null=True, verbose_name='ZIP Code Ext'),
        ),
    ]
