# Generated by Django 5.2.1 on 2026-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_district_remove_user_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='not_usa_phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='not_usa_state',
            field=models.CharField(max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
