# Generated by Django 5.2.1 on 2026-05-11 18:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_property_status_rentalbill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalbill',
            name='expense_amount',
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='bill_month',
            field=models.DateField(help_text='Use any date in the month. System will save it as first day of month.', verbose_name='Bill Month'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalized At'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_rental_bills', to=settings.AUTH_USER_MODEL, verbose_name='Finalized By'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_bills', to='accounts.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Rent Amount'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='base_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20, verbose_name='Base Weight'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='buyer_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Buyer Level'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='buyer_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Buyer Multiplier'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Contribution Amount'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='days_proportion',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20, verbose_name='Days Proportion'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='HFall Management Deduction'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='final_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Final Profit'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='final_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20, verbose_name='Final Weight'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Gross Profit'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Loss Amount'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='month_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Month Days'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='property_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_distributions', to='accounts.propertycontribution', verbose_name='Property Contribution'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='rental_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_lines', to='accounts.rentalbill', verbose_name='Rental Bill'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='shares',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20, verbose_name='Shares'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_distributions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='RentalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, verbose_name='Purpose')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Expense Amount')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='rental_expenses/receipts/', verbose_name='Receipt')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rental_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rental_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('paid_by_user', models.ForeignKey(blank=True, help_text='If any user paid this rental expense personally', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_rental_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Paid By User')),
                ('rental_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.rentalbill', verbose_name='Rental Bill')),
            ],
            options={
                'verbose_name': 'Rental Expense',
                'verbose_name_plural': 'Rental Expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
