# Generated by Django 5.2.1 on 2026-05-12 04:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_rentalbill_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbilldistribution',
            name='deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Deduction Percentage'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='bill_month',
            field=models.DateField(help_text='Use any date in the month. System will save it as the first day of that month.', verbose_name='Bill Month'),
        ),
        migrations.AlterField(
            model_name='rentalexpense',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, help_text='If any user paid this rental expense personally.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_rental_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Paid By User'),
        ),
    ]
