# Generated by Django 5.2.1 on 2026-05-12 06:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rentalbilldistribution_deduction_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbill',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='rentalbill',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rental_bills', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='rentalbill',
            name='rent_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='Rent Month'),
        ),
        migrations.AddField(
            model_name='rentalbill',
            name='rent_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent Year'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='bill_month',
            field=models.DateField(blank=True, help_text='Auto-generated from rent month and year.', null=True, verbose_name='Bill Month'),
        ),
        migrations.AlterField(
            model_name='rentalbill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='base_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='buyer_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='buyer_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='days_proportion',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='final_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='final_weight',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='month_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalbilldistribution',
            name='shares',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='rentalexpense',
            name='paid_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_rental_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Paid By User'),
        ),
    ]
