# Generated by Django 5.2.1 on 2026-05-23 16:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rentalbill_approved_at_rentalbill_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Withdraw Amount')),
                ('balance_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Balance Snapshot')),
                ('running_invest_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Running Invest Snapshot')),
                ('final_profit_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50, verbose_name='Final Profit Snapshot')),
                ('total_available_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance + running investment at request time.', max_digits=50, verbose_name='Total Request Limit Snapshot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved / Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('note', models.TextField(blank=True, null=True, verbose_name='User Note')),
                ('finance_note', models.TextField(blank=True, null=True, verbose_name='Finance Note')),
                ('clarification_note', models.TextField(blank=True, help_text='Finance note asking user for more clarification. Status remains pending.', null=True, verbose_name='Clarification Note')),
                ('clarification_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Clarification Requested At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('clarification_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarification_requested_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Clarification Requested By')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
