# Generated by Django 5.2.1 on 2026-06-22 09:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='final_profit_snapshot',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='note',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='running_invest_snapshot',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='total_available_snapshot',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='eligible_investment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='eligible_profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='invest_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_rule',
            field=models.CharField(choices=[('100_percent', '100% Profit Eligible'), ('45_percent', '45% Profit Eligible'), ('investment_only', 'Investment Only'), ('mixed', 'Investment + Profit')], default='45_percent', max_length=30),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='property_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='accounts.propertycontribution'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='request_type',
            field=models.CharField(choices=[('profit', 'Profit Only'), ('investment', 'Investment Only'), ('both', 'Investment + Profit')], default='profit', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='total_eligible_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='balance_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='clarification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='clarification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='clarification_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarification_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='finance_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved / Paid'), ('rejected', 'Rejected'), ('clarification', 'Need Clarification'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
