# Generated by Django 5.2.1 on 2026-06-22 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_withdrawalrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='balance_part_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='investment_part_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='profit_part_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=50),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_rule',
            field=models.CharField(choices=[('balance', 'Free Balance'), ('100_percent', '100% Profit Eligible'), ('45_percent', '45% Profit Eligible'), ('remaining_profit', 'Remaining Profit'), ('investment_only', 'Investment Only'), ('mixed', 'Investment + Profit')], default='45_percent', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_type',
            field=models.CharField(choices=[('balance', 'Free Balance'), ('profit', 'Profit Only'), ('investment', 'Investment Only'), ('both', 'Investment + Profit')], default='profit', max_length=20),
        ),
    ]
