# Generated by Django 5.2.1 on 2026-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_withdrawalrequest_balance_part_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycontribution',
            name='investment_type',
            field=models.CharField(choices=[('long_term', 'Long Term'), ('short_term', 'Short Term')], default='long_term', max_length=20, verbose_name='Investment Type Snapshot'),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_type',
            field=models.CharField(choices=[('long_term', 'Long Term'), ('short_term', 'Short Term')], default='long_term', max_length=20, verbose_name='Investment Type'),
        ),
    ]
