# Generated by Django 5.2.1 on 2026-07-03 15:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_propertycontribution_investment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycontribution',
            name='profit_proportion',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Sequence-wise profit proportion. Default comes from first/second level share. Admin can edit per sequence.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Profit Proportion (PP)'),
        ),
    ]
