# Generated by Django 5.2.1 on 2026-01-22 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_url', models.URLField(null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(blank=True, default=False, null=True)),
                ('meeting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_holder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(blank=True, default=False, null=True)),
                ('reminder_10min_sent', models.BooleanField(default=False, help_text='Email sent 10 minutes before meeting')),
                ('reminder_24hr_sent', models.BooleanField(default=False, help_text='Email sent 24 hours before meeting')),
                ('meeting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_schedule_holder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('recording_url', models.URLField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording', to='schedule.meetingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
