# Generated by Django 5.2.1 on 2026-04-16 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.CharField(blank=True, max_length=100, null=True)),
                ('end_time', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_url', models.URLField(null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(blank=True, default=False, null=True)),
                ('meeting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_holder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('series_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='All occurrences of a recurring meeting share the same series_id.')),
                ('occurrence_index', models.PositiveIntegerField(default=1, help_text='1-based position of this occurrence within the series.')),
                ('is_recurring', models.BooleanField(default=False, help_text='True only on the *first* occurrence (the series root).')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(blank=True, default=False, null=True)),
                ('reminder_10min_sent', models.BooleanField(default=False, help_text='Email sent 10 minutes before meeting')),
                ('reminder_24hr_sent', models.BooleanField(default=False, help_text='Email sent 24 hours before meeting')),
                ('enable_all_email_notification', models.BooleanField(default=False, help_text='Master switch – must be ON for any notice to be sent.')),
                ('notice_3_weeks', models.BooleanField(default=False)),
                ('notice_2_weeks', models.BooleanField(default=False)),
                ('notice_1_week', models.BooleanField(default=False)),
                ('notice_1_day', models.BooleanField(default=False)),
                ('notice_10_min', models.BooleanField(default=False)),
                ('meeting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_schedule_holder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('recording_url', models.URLField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recording', to='schedule.meetingschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingEmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('3w', '3 Weeks'), ('2w', '2 Weeks'), ('1w', '1 Week'), ('1d', '1 Day'), ('10m', '10 Minutes')], max_length=10)),
                ('scheduled_for', models.DateTimeField()),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedules', to='schedule.meetingschedule')),
            ],
            options={
                'unique_together': {('meeting', 'notice_type')},
            },
        ),
    ]
