# Generated by Django 5.2.1 on 2026-04-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_meetingschedule_guests"),
    ]

    operations = []
