# Generated by Django 5.2.1 on 2026-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingschedule',
            name='guests',
            field=models.ManyToManyField(blank=True, help_text='Users who have any of these tags will receive email.', related_name='meetings', to='schedule.tag'),
        ),
    ]
