# Generated by Django 5.2.1 on 2026-04-16 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='enable_all_email_notification',
            field=models.BooleanField(default=False, help_text='Master switch – must be ON for any notice to be sent.'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='True only on the *first* occurrence (the series root).'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='notice_10_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='notice_1_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='notice_1_week',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='notice_2_weeks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='notice_3_weeks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='occurrence_index',
            field=models.PositiveIntegerField(default=1, help_text='1-based position of this occurrence within the series.'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='series_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='All occurrences of a recurring meeting share the same series_id.'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='guests',
            field=models.ManyToManyField(blank=True, help_text='Users who have any of these tags will receive email.', related_name='meetings', to='schedule.tag'),
        ),
        migrations.CreateModel(
            name='MeetingEmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('3w', '3 Weeks'), ('2w', '2 Weeks'), ('1w', '1 Week'), ('1d', '1 Day'), ('10m', '10 Minutes')], max_length=10)),
                ('scheduled_for', models.DateTimeField()),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedules', to='schedule.meetingschedule')),
            ],
            options={
                'unique_together': {('meeting', 'notice_type')},
            },
        ),
    ]
